---

- name: Check if rustup is installed
  ansible.builtin.command: which rustup
  changed_when: false
  failed_when: false
  register: rust_rustup_install_check
  environment:
    PATH: "{{ ansible_user_dir }}/.cargo/bin:{{ ansible_env.PATH }}"

- name: Install rustup
  when: rust_rustup_install_check.rc != 0
  block:
    - name: create temporary file to hold rustup installer script
      ansible.builtin.tempfile:
        state: file
        suffix: _rustup_installer.tmp
      register: rust_rustup_tmp_installer
      notify: Remove rustup installer

    - name: Grab rustup installer content
      ansible.builtin.uri:
        url: https://sh.rustup.rs
        return_content: true
        status_code:
          - 304
          - 200
      register: rust_rustup_tmp_installer_response

    - name: Copy installer content to temporary file
      ansible.builtin.copy:
        content: "{{ rust_rustup_tmp_installer_response.content }}"
        dest: "{{ rust_rustup_tmp_installer.path }}"
        mode: "0755"

    - name: Run rustup installer script
      ansible.builtin.script: "{{ rust_rustup_tmp_installer.path }} -y"

- name: Set default rustup toolchain
  ansible.builtin.command: rustup default nightly
  environment:
    PATH: "{{ ansible_user_dir }}/.cargo/bin:{{ ansible_env.PATH }}"

- name: Add rust language server requisites
  ansible.builtin.command: rustup component add rls rust-analysis rust-analyzer rust-src
  environment:
    PATH: "{{ ansible_user_dir }}/.cargo/bin:{{ ansible_env.PATH }}"
