---

# This playbook installs archlinux on a new partition following the LVM on LUKS
# strategy here:
#
#   https://wiki.archlinux.org/index.php/Dm-crypt/Encrypting_an_entire_system#LVM_on_LUKS.
#
# This requires both a LUKS partition and an EFI system partition to exist
# beforehand (since handling all possible scenarios would take a ton of
# coordination). Instructions are in the README.md.
#
# More notes and post-installation steps, especially regarding LUKS and using
# keyfiles, are in the README.

- hosts: localhost
  vars_files:
    - roles/bootstrap/defaults/main.yaml
  tasks:
    - name: ensure that an EFI system partition is defined
      assert:
        that:
          - install_esp is defined
        fail_msg: "An ESP must be defined, for example /dev/sda1"

    - name: ensure that an installation partition is defined
      assert:
        that:
          - install_partition is defined
        fail_msg: "An installation partition must be defined, for example /dev/sda2"

    - name: ensure a FAT32 filesystem exists on the ESP
      community.general.filesystem:
        device: "{{ install_esp }}"
        type: vfat
        opts: -F 32

    - name: create volume group on {{ install_partition }}
      community.general.lvg:
        pvs: "{{ install_partition }}"
        vg: vogr
        pvresize: yes

    - name: create logical volume for main data
      community.general.lvol:
        vg: vogr
        lv: main
        size: 90%FREE # leave 10% for snapshots

    - name: create ext4 filesystem on main partition
      community.general.filesystem:
        device: /dev/mapper/vogr-main
        type: ext4

    - name: mount /dev/mapper/vogr-main to /mnt
      ansible.posix.mount:
        src: /dev/mapper/vogr-main
        path: /mnt
        fstype: ext4
        state: mounted

    - name: mount ESP to /mnt/boot
      ansible.posix.mount:
        src: "{{ install_esp }}"
        path: /mnt/boot
        fstype: vfat
        state: mounted

    - name: sync time
      command: timedatectl set-ntp true
      changed_when: false

    - name: pacstrap dat boi
      command: pacstrap /mnt base linux linux-firmware lvm2 {{ bootstrap_packages.archlinux | join(" ") }}

    - name: generate system fstab
      shell: genfstab -U /mnt >> /mnt/etc/fstab

    - name: clone dotfiles into /mnt/tmp/dotfiles
      git:
        repo: https://github.com/j4ns8i/dotfiles
        dest: /mnt/tmp/dotfiles

    - debug:
        msg: Initial installation done - be sure to run the arch-chroot into /mnt and run the bootstrap playbook
