# https://taskfile.dev

version: '3'

tasks:
  default:
    desc: List all tasks
    cmds:
      - task -l
    silent: true

  switch:
    desc: Build and switch to the latest home-manager config
    cmds:
      - home-manager switch
    aliases:
      - sw

  format:
    desc: Format all Nix files
    cmds:
      - fd -e nix | xargs nixfmt
