# File structure:
# ❯ tree ~/.config/zsh
# ~/.config/zsh
# ├── completions
# │   ├── _ggo
# │   ├── _ggr
# │   ├── _nvm -> ~/code/src/github.com/robbyrussell/oh-my-zsh/plugins/nvm/_nvm
# │   ├── _pip
# │   ├── _status
# │   └── _track
# ├── functions
# │   ├── async
# │   ├── colored-man-pages.plugin.zsh
# │   ├── nvm.plugin.zsh -> ~/code/src/github.com/robbyrussell/oh-my-zsh/plugins/nvm/nvm.plugin.zsh
# │   ├── pip.plugin.zsh
# │   └── prompt_pure_setup
# └── runcommands
#     ├── atg.zsh -> ~/code/src/git.viasat.com/ATG/stdlib/bash/atg.sh
#     ├── lfcd.sh -> ~/code/src/github.com/gokcehan/lf/etc/lfcd.sh
#     ├── local.zsh
#     ├── viasat.zsh
#     └── zsh-history-substring-search.zsh -> ~/code/src/github.com/zsh-users/zsh-history-substring-search/zsh-history-substring-search.zsh
# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

export ZSH_CONFIG_DIR=~/.config/zsh

fpath=(${ZSH_CONFIG_DIR}/functions ${ZSH_CONFIG_DIR}/completions $fpath)

# The following lines were added by compinstall

zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle ':completion:*' completions 1
zstyle ':completion:*' expand prefix suffix
zstyle ':completion:*' glob 1
zstyle ':completion:*' group-name ''
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}" # color completions according to LS_COLORS
# zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-suffixes true
zstyle ':completion:*' menu select # highlight selected menu items
zstyle ':completion:*' substitute 1
zstyle :compinstall filename '/Users/jsmalkowski/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

for rc in ${ZSH_CONFIG_DIR}/runcommands/*; do
    source $rc
done

# <up> and <down> searches history for something beginning with the current
# line (up to the cursor)
bindkey "${key[Up]}"   history-beginning-search-backward
bindkey "${key[Down]}" history-beginning-search-forward

# shift-tab reverses menu completion
bindkey '^[[Z' reverse-menu-complete

bindkey -s '^o' 'lfcd\n'

# for rc in ${ZSH_CONFIG_DIR}/functions/*; do
#     source $rc
# done

autoload -U zmv
autoload -U promptinit; promptinit
zstyle :prompt:pure:prompt:success color 2
zstyle :prompt:pure:prompt:error   color 1
zstyle :prompt:pure:virtualenv     color 8
zstyle :prompt:pure:git:branch     color 8
zstyle :prompt:pure:git:action     color 8
zstyle :prompt:pure:git:dirty      color 13
zstyle :prompt:pure:git:arrow      color 6
prompt pure

# load fzf configuration
if [[ -f ~/.fzf.zsh ]]; then
    source ~/.fzf.zsh
fi
