---

- name: Include tasks for {{ ansible_os_family | lower }} if defined
  ansible.builtin.include_tasks: "{{ item }}"
  with_fileglob: "{{ ansible_os_family | lower }}.yaml"

- name: Symlink ./links to {{ direnv_config_dir }}
  ansible.builtin.file:
    src: "{{ direnv_link_base }}/links"
    dest: "{{ direnv_config_dir }}"
    state: link
