---

- name: include tasks for {{ ansible_os_family | lower }} if defined
  include_tasks: "{{ item }}"
  with_fileglob: "{{ ansible_os_family | lower }}.yaml"

- name: ln -s links {{ direnv_config_dir }}
  file:
    src: "{{ direnv_link_base }}/links"
    dest: "{{ direnv_config_dir }}"
    state: link
