---

- name: include tasks for {{ ansible_os_family }} if defined
  include_tasks: "{{ item }}"
  with_fileglob: "{{ ansible_os_family | lower }}.yaml"

- name: pyenv install 3.11.7
  ansible.builtin.command: pyenv install --skip-existing 3.11.7

  # pipx should be globally installed, and we'll have to tell the pipx module
  # where it is
- name: which pipx
  ansible.builtin.command: which pipx
  changed_when: false
  register: python_pipx_path

- name: pipx install pipenv
  community.general.pipx:
    name: pipenv
    state: present
    executable: "{{ python_pipx_path.stdout }}"

- name: pipx install poetry
  community.general.pipx:
    name: poetry
    state: present
    executable: "{{ python_pipx_path.stdout }}"
