---

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

docker_apt_key_url: "https://download.docker.com/linux/{{ ansible_distribution|docker_distro }}/gpg"
docker_apt_key_dest: /etc/apt/keyrings/docker.gpg
docker_apt_repo_url: "deb [arch=amd64 signed-by={{ docker_apt_key_dest }}] https://download.docker.com/{{ ansible_system|lower }}/{{ ansible_distribution|docker_distro }} {{ ansible_distribution_release|lower }} stable"
