import = [
    "~/.config/alacritty/os.toml",
    "~/.config/alacritty/colors.toml",
]

[font]
size = 14

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "Regular"

# If needed, the styles can be further customized below

[font.italic]
style = "Italic"

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.offset]
x = 0
y = 0

[[hints.enabled]]
command = "open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B."
key = "Period"
mods = "Alt"

[mouse]
hide_when_typing = true

[window.padding]
x = 4
y = 4
