import = [
    "~/.config/alacritty/os.toml",
]

[colors.primary]
background = "#15171d"
foreground = "#c7d0e0"

[colors.cursor]
text   = "#c7d0e0"
cursor = "#424449"

[colors.selection]
text       = '#c7d0e0'
background = '#303238'

[colors.normal]
black   = "#15171d"
red     = "#d4737f"
green   = "#90b782"
yellow  = "#ffcda4"
blue    = "#86a5be"
magenta = "#8f729a"
cyan    = "#76af9d"
white   = "#424449"

[colors.bright]
black   = "#303238"
red     = "#c45361"
green   = "#607f55"
yellow  = "#d6ae86"
blue    = "#4b799e"
magenta = "#9b68b3"
cyan    = "#487e6d"
white   = "#c7d0e0"

# [colors.hints]
# start = { foreground = '#908caa', background = '#2a273f' }
# end =   { foreground = '#6e6a86', background = '#2a273f' }

[font]
size = 14

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "ExtraLight Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "ExtraLight"

[font.offset]
x = 0
y = 0

[[hints.enabled]]
command = "open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B."
key = "Period"
mods = "Alt"

[mouse]
hide_when_typing = true

[window.padding]
x = 4
y = 4
