---

- name: Include installation tasks for {{ ansible_os_family | lower }} if defined
  ansible.builtin.include_tasks: "{{ item }}"
  with_fileglob: "install.*{{ ansible_os_family | lower }}*.yaml"

- name: Symlink ./links/zshrc to {{ dotfiles_home_dir }}/.zshrc
  ansible.builtin.file:
    src: "{{ zsh_link_base }}/links/zshrc"
    dest: "{{ dotfiles_home_dir }}/.zshrc"
    state: link

- name: Create {{ zsh_config_dir }}
  ansible.builtin.file:
    path: "{{ zsh_config_dir }}"
    state: directory
    mode: "0700"

- name: Create {{ zsh_config_dir }}/completions
  ansible.builtin.file:
    path: "{{ zsh_config_dir }}/completions"
    state: directory
    mode: "0700"

- name: Symlink ./links/share to {{ zsh_config_dir }}/share
  ansible.builtin.file:
    src: "{{ zsh_link_base }}/links/share"
    dest: "{{ zsh_config_dir }}/share"
    state: link

- name: Symlink ./links/{{ ansible_os_family | lower }}.zsh to {{ zsh_config_dir }}/os.zsh
  ansible.builtin.file:
    src: "{{ os_config_file }}"
    dest: "{{ zsh_config_dir }}/os.zsh"
    state: link
  with_fileglob:
    - "{{ zsh_link_base }}/links/{{ ansible_os_family | lower }}.zsh"
  loop_control:
    loop_var: os_config_file

- name: Create {{ zsh_config_dir }}/functions
  ansible.builtin.file:
    path: "{{ zsh_config_dir }}/functions"
    state: directory
    mode: "0700"

- name: Clone https://github.com/sindresorhus/pure under {{ zsh_config_dir }}/pure
  ansible.builtin.git:
    repo: https://github.com/sindresorhus/pure
    dest: "{{ zsh_config_dir }}/pure"
