---

- name: install zsh
  ansible.builtin.package:
    name: zsh
    state: present
  become: "{{ ansible_os_family|lower != 'darwin' }}"

- name: ln -sf links/zshrc {{ dotfiles_home_dir }}/.zshrc
  file:
    src: "{{ zsh_link_base }}/links/zshrc"
    dest: "{{ dotfiles_home_dir }}/.zshrc"
    state: link

- name: mkdir ~/.config/zsh
  ansible.builtin.file:
    path: "{{ zsh_config_dir }}"
    state: directory

- name: ln -sf links/share {{ zsh_config_dir }}/share/
  ansible.builtin.file:
    src: "{{ zsh_link_base }}/links/share"
    dest: "{{ zsh_config_dir }}/share"
    state: link

- name: ln -sf links/{{ ansible_os_family|lower }}.zsh {{ zsh_config_dir }}/os.zsh
  ansible.builtin.file:
    src: "{{ item }}"
    dest: "{{ zsh_config_dir }}/os.zsh"
    state: link
  with_fileglob:
    - "{{ zsh_link_base }}/links/{{ ansible_os_family|lower }}.zsh"

- name: mkdir {{ zsh_config_dir }}/functions
  file:
    path: "{{ zsh_config_dir }}/functions"
    state: directory

- name: clone https://github.com/sindresorhus/pure
  git:
    repo: https://github.com/sindresorhus/pure
    dest: "{{ zsh_config_dir }}/pure"
