---

- name: install kitty packages
  ansible.builtin.package:
    name: "{{ package }}"
    state: latest
  loop: ["kitty", "kitty-doc", "kitty-terminfo"]
  loop_control:
    loop_var: package
  become: yes

- name: import kitty config tasks
  ansible.builtin.import_tasks: config.yaml
