---

- name: Install kitty packages
  ansible.builtin.package:
    name: "{{ package }}"
    state: latest
  loop: ["kitty", "kitty-doc", "kitty-terminfo"]
  loop_control:
    loop_var: package
  become: true
