local function run_in_tmux() {
    tmux new-session
    exit 0 # exit out after the session ends or is detached
}

local function run_normally() {
    # Uncomment for profiling
    # zmodload zsh/zprof

    export ZSH_CONFIG_DIR=~/.config/zsh

    fpath=(
        ${ZSH_CONFIG_DIR}/pure
        ${ZSH_CONFIG_DIR}/functions
        ${ZSH_CONFIG_DIR}/completions
        ${ZSH_CONFIG_DIR}/share/functions
        ${ZSH_CONFIG_DIR}/share/completions
        $fpath
    )

    # (N) sets NULL_GLOB to return nothing when no matches are found.
    # See `man zshexpn` > Glob Qualifiers.
    for rc in ${ZSH_CONFIG_DIR}/*.zsh(N); do source $rc; done
    for rc in ${ZSH_CONFIG_DIR}/share/runcommands/*.zsh(N); do source $rc; done
    for rc in ${ZSH_CONFIG_DIR}/after/*.zsh(N); do source $rc; done

    # Uncomment for profiling
    # zprof
}

# if TMUX is set or if you don't have tmux, load normally
if [[ -n "$TMUX" ]] || ! command -v tmux &>/dev/null; then
    run_normally
else
    run_in_tmux
fi
