---

- name: install tmux
  package:
    name: tmux
    state: present
  become: "{{ ansible_os_family|lower != 'darwin' }}"

- name: ln -sf tmux.conf ~/.tmux.conf
  ansible.builtin.file:
    src: "{{ tmux_link_base }}/links/tmux.conf"
    dest: "{{ dotfiles_home_dir }}/.tmux.conf"
    state: link

- name: mkdir {{ tmux_config_dir }}
  ansible.builtin.file:
    path: "{{ tmux_config_dir }}"
    state: directory

- name: ln -sf {{ ansible_os_family|lower }}.conf {{ tmux_config_dir }}/os.conf
  ansible.builtin.file:
    src: "{{ tmux_link_base }}/links/{{ ansible_os_family|lower }}.conf"
    dest: "{{ tmux_config_dir }}/os.conf"
    state: link
