---

- name: Install tmux
  ansible.builtin.package:
    name: tmux
    state: present
  become: "{{ ansible_os_family | lower != 'darwin' }}"

- name: Symlink ./links/tmux.conf to ~/.tmux.conf
  ansible.builtin.file:
    src: "{{ tmux_link_base }}/links/tmux.conf"
    dest: "{{ dotfiles_home_dir }}/.tmux.conf"
    state: link

- name: Create {{ tmux_config_dir }}
  ansible.builtin.file:
    path: "{{ tmux_config_dir }}"
    state: directory
    mode: "0700"

- name: Symlink {{ ansible_os_family | lower }}.conf to {{ tmux_config_dir }}/os.conf
  ansible.builtin.file:
    src: "{{ tmux_link_base }}/links/{{ ansible_os_family | lower }}.conf"
    dest: "{{ tmux_config_dir }}/os.conf"
    state: link

- name: Symlink ./links/vim-tmux-navigator.conf to {{ tmux_config_dir }}/vim-tmux-navigator.conf
  ansible.builtin.file:
    src: "{{ tmux_link_base }}/links/vim-tmux-navigator.conf"
    dest: "{{ tmux_config_dir }}/vim-tmux-navigator.conf"
    state: link
