python_pyenv_dependencies:
  debian:
    - make
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - wget
    - curl
    - llvm
    - libncursesw5-dev
    - xz-utils
    - tk-dev
    - libxml2-dev
    - libxmlsec1-dev
    - libffi-dev
    - liblzma-dev
  darwin:
    - openssl
    - readline
    - sqlite3
    - xz
    - zlib
    - tcl-tk
  archlinux:
    - openssl
    - zlib
    - xz
    - tk
