---

- name: Clean up kitty download
  ansible.builtin.file:
    path: "{{ kitty_dmg_download_tempfile.path }}"
    state: absent

- name: Clean up kitty mount dir
  ansible.builtin.file:
    path: "{{ kitty_dmg_tempdir.path }}"
    state: absent
