#!/bin/bash


# This script wipes out a given drive, recreates the partition table, recreates
# the ESP and root partitions, then runs the proper ansible-playbook command to
# begin a new installation. Run with care.
#
# IMPORTANT this script assumes a 200GiB partition size. Modify if necessary.

usage() {
	echo "reinstall-arch DEVICE [SIZE]"
	exit 1
}

main() {
	local device=$1
	if [[ "$device" == "" ]]; then
		usage
	fi

	local size=${2:-200GiB}

	set -e
	echo "Recreating partition table on $1 with root partition size ${size}"
	wipefs -a $device
	sfdisk /dev/sda <<< 'label: gpt'
	sfdisk --label gpt /dev/sda -N 1 <<< 'start=1MiB, size=512MiB, type=U'
	sfdisk --label gpt /dev/sda -N 2 <<< 'start=513MiB, size=200GiB, type=L'

	local esp_partition="${device}1"
	local root_partition="${device}2"
	echo "Running ansible using $esp_partition as ESP and $root_partition as root partition"
	ansible-playbook install_archlinux.yaml -e install_esp=$esp_partition -e install_partition=$root_partition
}

main $@
