---

- name: include debian vars
  include_vars: debian.yaml

- name: install prerequisites
  package:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: add apt key
  ansible.builtin.shell:
    cmd: "curl -fsSL {{ docker_apt_key_url }} | gpg -o {{ docker_apt_key_dest }} --dearmor"
    creates: "{{ docker_apt_key_dest }}" # delete this file if a refresh is needed
  become: true

- name: add apt repo
  ansible.builtin.apt_repository:
    repo: "{{ docker_apt_repo_url }}"
    state: present
  become: true

- name: install docker packages
  package:
    name: "{{ docker_packages }}"
    state: present
  become: true

- name: add {{ ansible_user }} to docker group
  ansible.builtin.user:
    user: "{{ ansible_user_id }}"
    groups: docker
    append: true
  become: true
