---

- name: install alacritty package
  package:
    name: alacritty
    state: present
  become: "{{ ansible_os_family|lower != 'darwin' }}"

- name: "create dir: {{ alacritty_config_dir }}"
  file:
    path: "{{ alacritty_config_dir }}"
    state: directory

- name: ln -sf alacritty.toml ~/.config/alacritty/alacritty.toml
  ansible.builtin.file:
    state: link
    src: "{{ alacritty_link_base }}/files/alacritty.toml"
    dest: "{{ alacritty_config_dir }}/alacritty.toml"

- name: ln -sf {{ ansible_os_family|lower }}.toml ~/.config/alacritty/os.toml
  ansible.builtin.file:
    state: link
    src: "{{ alacritty_link_base }}/files/{{ ansible_os_family|lower }}.toml"
    dest: "{{ alacritty_config_dir }}/os.toml"
