---

- name: Include tasks for {{ ansible_os_family | lower }} if defined
  ansible.builtin.include_tasks: "{{ item }}"
  with_fileglob: "{{ ansible_os_family | lower }}.yaml"

- name: Create {{ alacritty_config_dir }}
  ansible.builtin.file:
    path: "{{ alacritty_config_dir }}"
    state: directory
    mode: "0700"

- name: Symlink Alacritty config files
  ansible.builtin.file:
    state: link
    src: "{{ alacritty_link_base }}/links/{{ config_file }}"
    dest: "{{ alacritty_config_dir }}/{{ config_file }}"
  with_items:
    - alacritty.toml
    - colors.toml
  loop_control:
    loop_var: config_file

- name: Symlink {{ ansible_os_family | lower }}.toml to ~/.config/alacritty/os.toml
  ansible.builtin.file:
    state: link
    src: "{{ os_config_file }}"
    dest: "{{ alacritty_config_dir }}/os.toml"
  with_fileglob: "{{ alacritty_link_base }}/links/{{ ansible_os_family | lower }}.toml"
  loop_control:
    loop_var: os_config_file
