---

- hosts: localhost
  roles:
    - role: homebrew
      tags: homebrew

    - role: bootstrap
      tags: bootstrap

    - role: fonts
      tags: fonts

    - role: zsh
      tags: zsh

    - role: tmux
      tags: tmux

    - role: kitty
      tags: kitty

    - role: zoxide
      tags: zoxide

    - role: rust
      tags: rust

    - role: fzf
      tags: fzf

    - role: direnv
      tags: direnv

    - role: python
      tags: python

    - role: go
      tags: go

    - role: node
      tags: node

    - role: neovim
      tags: neovim

    - role: gcloud
      tags: gcloud
