---

- name: Include tasks for {{ ansible_os_family }} if defined
  ansible.builtin.include_tasks: "{{ item }}"
  with_fileglob: "{{ ansible_os_family | lower }}.yaml"

- name: Symlink ./links/config/nvim to {{ neovim_config_dir }}
  ansible.builtin.file:
    src: "{{ neovim_link_base }}/links/config/nvim"
    dest: "{{ neovim_config_dir }}"
    state: link

- name: Run `nvim --headless "+Lazy! sync" +qa`
  ansible.builtin.command: nvim --headless "+Lazy! sync" +qa
  when: ansible_user_id != "root"
  changed_when: false
  environment:
    PATH: "{{ ansible_env.PATH }}"
