---

- name: include tasks for {{ ansible_os_family }} if defined
  include_tasks: "{{ item }}"
  with_fileglob: "{{ ansible_os_family | lower }}.yaml"

- name: ln -sf files/config/nvim {{ neovim_config_dir }}
  file:
    src: "{{ neovim_link_base }}/files/config/nvim"
    dest: "{{ neovim_config_dir }}"
    state: link

- name: nvim --headless "+Lazy! sync" +qa
  ansible.builtin.command: nvim --headless "+Lazy! sync" +qa
  when: ansible_user_id != "root"
  changed_when: false
