---

- name: include tasks for {{ ansible_os_family }} if defined
  include_tasks: "{{ item }}"
  with_fileglob: "{{ ansible_os_family | lower }}.yaml"

- name: link neovim config dir
  file:
    path: "{{ neovim_link_base }}/files/config/nvim"
    dest: "{{ neovim_config_dir }}"
    state: link

- name: link .vimrc to init.lua
  file:
    path: "{{ neovim_link_base }}/config/nvim/init.lua"
    dest: "{{ dotfiles_home_dir }}/.vimrc"
    state: link

- name: install vim plugins
  command: nvim -es -u {{ neovim_config_dir }}/init.lua -i NONE -c "PackerSync" -c "qa"
  when: ansible_user_id != "root"
  changed_when: false
