name: "Lock and sync python dependencies"

on:
  pull_request:
    types:
      - opened
    branches:
      - master
    paths:
      - 'Pipfile'
      - 'Pipfile.lock'

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install pipenv
        run: pipx install pipenv
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pipenv'
      - name: Lock and sync python dependencies
        id: lock
        run: |
          pipenv lock
          pipenv requirements > requirements.txt
          if [[ -z "$(git status --porcelain)" ]]; then
            echo "dirty=false" >> $GITHUB_OUTPUT
          else
            echo "dirty=true" >> $GITHUB_OUTPUT
          fi
      - name: Commit and push changes
        if: ${{ steps.lock.outputs.dirty == 'true' }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Pipfile Pipfile.lock requirements.txt
          git commit -m "Lock and sync python dependencies"
          git push
