name: "Lock and sync poetry.lock and requirements.txt"

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
    paths:
      - 'pyproject.toml'
      - 'poetry.lock'

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install poetry
        run: |
          pipx install poetry
          pipx inject poetry poetry-plugin-export
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'poetry'
      - name: Lock and sync poetry.lock and requirements.txt
        id: lock
        run: |
          poetry lock
          poetry export -f requirements.txt > requirements.txt
          if [[ -z "$(git status --porcelain)" ]]; then
            echo "dirty=false" >> $GITHUB_OUTPUT
          else
            echo "dirty=true" >> $GITHUB_OUTPUT
          fi
      - name: Commit and push changes
        if: ${{ steps.lock.outputs.dirty == 'true' }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add poetry.lock requirements.txt
          git commit -m "ci: lock and sync poetry.lock and requirements.txt"
          git push
