---

- name: Download JetBrainsMono Nerd Font
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.zip
    remote_src: true
    dest: /usr/local/share/fonts/
    mode: "0644"
  become: true

- name: Download MapleMono NF
  ansible.builtin.unarchive:
    src: https://github.com/subframe7536/maple-font/releases/latest/download/MapleMono-ttf.zip
    remote_src: true
    dest: /usr/local/share/fonts/
    mode: "0644"
  become: true

- name: Run fc-cache
  ansible.builtin.command: fc-cache
